version: '3.8'
services:
  mysql:
    image: mysql:8.0.19
    restart: always
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
    networks:
      - admetric_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_TCP_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DB}
  
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - admetric_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  redis_data:

networks:
  admetric_network:
    name: admetric_network
    driver: bridge